### ISSUE TITLE
react-native link

### ISSUE THREAD

**Issue by Ehesp** [AppsFlyerSDK/react-native-appsflyer#1]
Hi, would it be possible to add the react-native link CLI to this project?

**Comment by af-fess** [comment]
@Ehesp can you clarify?

**Comment by Ehesp** [comment]
Sure. Instead of manually setting the iOS /Android workflow which is currently in the readme, it'd be cool if we could just run 'react-native link react-native-appsflyer', this would automatically update all the required files without the need for manual intervention. This is handy when you've got an automated build script for the apps. 

If you look at https://github.com/zo0r/react-native-push-notification/blob/master/README.md they do this among many other libs. 

Docs;

https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by af-fess** [comment]
@Ehesp make sense, we will check it out. Thanks,

**Comment by jlo1** [comment]
Seems like `react-native link` works fine for android, but breaks for ios?
```
rnpm-install info Linking react-native-appsflyer android dependency 
rnpm-install info Android module react-native-appsflyer has been successfully linked 
rnpm-install info Linking react-native-appsflyer ios dependency 
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "{" but "/" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 
```

Might be related to https://github.com/facebook/react-native/issues/10032

**Comment by Ehesp** [comment]
Also getting this issue.

**Comment by af-fess** [comment]
`$ react-native unlink react-native-appsflyer`

```
Scanning folders for symlinks in /Users/maxim/Appsflyer/projects/DEMOS/REACT_NATIVE/DemoPod3/node_modules (13ms)
rnpm-install info Unlinking react-native-appsflyer ios dependency 
rnpm-install info Platform 'ios' module undefined has been successfully unlinked 
rnpm-install info Unlinking react-native-appsflyer android dependency 
rnpm-install info Platform 'android' module undefined has been successfully unlinked 
```

Closed because of non-activity
