### ISSUE TITLE
initSdk: undefined error on iOS

### ISSUE THREAD

**Issue by SMJ93** [AppsFlyerSDK/react-native-appsflyer#10]
I have already looked at https://github.com/AppsFlyerSDK/react-native-appsflyer/issues/3, but this does not fix my issue.

I have followed the read me steps:

- yarn add react-native-appsflyer --save
- pod file:
```
use_frameworks!
project 'ios/SportEventApp.xcodeproj'

target 'SportEventApp' do
  pod 'AppsFlyerFramework'
end
```
- pod install --verbose
- Add NAppsFlyer.xcodeproj to libraries in xcode
- Add libRNAppsFlyer.a to Link binaries with libraries

At this stage the project didn't build. I got an error: `linker command failed with exit code 1 (use -v to see invocation)` pointing to the `Pods_SportEventApp.framework` file in `Linked binaries with libraries`.

I found [this](http://stackoverflow.com/questions/31139534/pod-error-in-xcode-id-framework-not-found-pods) solution which said to remove the `Pods_SportEventApp.framework` from `Linked binaries with libraries`.

The app now runs fine on both iOS simulator and iOS device, but in the console log I get: 

`initSdk: undefined`

I am using:

- AppsFlyerFramework 4.6.1
- react-native-cli: 1.0.0
- react-native: 0.37.0
- Xcode Version 8.2.1

Here are all of my Linked Framework and Libraries:
![screen shot 2017-01-09 at 16 57 56](https://cloud.githubusercontent.com/assets/2145641/21775126/d816242e-d68c-11e6-8aef-15d9f963c1d8.png)

**Comment by af-fess** [comment]
@SMJ93 hi, I tried to run AppsFlyer pod on [demo](https://github.com/AppsFlyerSDK/react-native-appsflyer/tree/master/demo) and it works as expected. 

regards to your env. : you use `react-native: 0.37.0` but `react-native-cli: 1.0.0` looks old. Today we have `react-native-cli: 2.0.1` . But before upgrade try to run the demo:

from plugin root run (clone it first from git repo):
```
$ npm run setup
$ npm run ios-pod
$ npm run demo.ios
```

let me know how it works on your side.

**Comment by SMJ93** [comment]
@af-fess, thanks for the quick response. I have tested the demo project and it works for me.

I will completely reinstall the plugin with the updated `cli` and hope that works.

**Comment by SMJ93** [comment]
@af-fess  Finally. I managed to get this working. The problem is with the `init` example in the docs: https://github.com/AppsFlyerSDK/react-native-appsflyer.

It says:

```
let options = {
       devKey:  'WdpTVAcYwmxsaQ4WeTspmh',
       appId: "975313579",
       isDebug: true
     };

    appsFlyer.initSdk(options, (error, result) => { <------- HERE IS THE PROBLEM
      if (error) {
        console.error(error);
      } else {
       //..
      }
    })
```

The function should be replaced with:

```
appsFlyer.initSdk(options,
    (result) => {
	console.log(result)
    },
    (error) => {
	console.error(error);
    }
)
```

**Comment by af-fess** [comment]
@SMJ93 right, we will update Docs, good catch
