### ISSUE TITLE
Wrapper doesn't have getAppsFlyerUID for Android

### ISSUE THREAD

**Issue by iagorm** [AppsFlyerSDK/react-native-appsflyer#103]
# Report
This package doesn't cover method `getAppsFlyerUID` for Android.

## Plugin Version
1.4.4

## On what Platform are you having the issue?
Android

## What did you do?
Yarn install

## What did you expect to happen?
To access `getAppsFlyerUID` for Android

## What happened instead?
returns null because the function works only for iOS

## Please provide any other relevant information.
React native: 0.59.3

**Comment by wesfieldj** [comment]
@iagorm 

Can you try to run the following code: 
```javascript
appsFlyer.getAppsFlyerUID((error, appsFlyerUID)=>{alert(appsFlyerUID)})
```

We tested this on our end and we were not able to reproduce the issue. 
The code above worked for us. 

Let us know if the code above does not work for you. 

Thanks!

**Comment by iagorm** [comment]
> @iagorm
> 
> Can you try to run the following code:
> 
> ```js
> appsFlyer.getAppsFlyerUID((error, appsFlyerUID)=>{alert(appsFlyerUID)})
> ```
> 
> We tested this on our end and we were not able to reproduce the issue.
> The code above worked for us.
> 
> Let us know if the code above does not work for you.
> 
> Thanks!

@wesfieldj, this code works but the index.js doesn't have the structure like this, so I thought the `callback` was more with the data itself.

```
appsFlyer.getAppsFlyerUID = callback => {
  return RNAppsFlyer.getAppsFlyerUID(callback);
};
```
