### ISSUE TITLE
"onInstallConversionData" event can not be listen  on iOS 

### ISSUE THREAD

**Issue by zhanghaoalloc** [AppsFlyerSDK/react-native-appsflyer#105]
I found "onInstallConversionData"  event can not be listening.The reason that Author use  
Outdated function   "[self.bridge.eventDispatcher sendAppEventWithName:afOnInstallConversionData body:data];" in Class  RNAppsFlyers . Apple use  NativeEventEmitter  instead of  NativeAppEventEmitter. This  problem make we can not listen to  "onInstallConversionData" event. So I wish this problem can be solved in last version.
Best wish with you.

**Comment by wesfieldj** [comment]
@zhanghaoalloc Thanks for pointing this out. We will see what we can do to improve this for the next release.
