### ISSUE TITLE
[ Android ] onInstallConversionData cannot be listen

### ISSUE THREAD

**Issue by tamago3keran** [AppsFlyerSDK/react-native-appsflyer#111]
# Report

The event is not listening to the `onInstallConversionData` on Android.
(I checked working `onInstallConversionData` on 1.4.4)

## Plugin Version

1.4.5

## On what Platform are you having the issue?

Android

## What did you do?

```javascript
appsFlyer.onInstallConversionData(appsFlyerMetadata => {
  console.log("onInstallConversionData is called");
});
```

## What did you expect to happen?

On "Debug JS Remotely", printing words on Web Console.

## What happened instead?

Nothing happens.

## Please provide any other relevant information.

I changed code as the following, and `onInstallConversionData` became working.

`android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java`

```diff
  private void handleSuccess(String eventType, Map<String, String> data) {
      JSONObject obj = new JSONObject();
  
      try {
          obj.put("status", afSuccess);
          obj.put("type", eventType);
          obj.put("data", new JSONObject(data));
          if (eventType.equals(afOnInstallConversionDataLoaded)) {
-             sendEvent(reactContext, afOnInstallConversionData, obj.toString());
+             sendEvent(reactContext, afOnInstallConversionDataLoaded, obj.toString());
          } else if (eventType.equals(afOnAppOpenAttribution)) {
              sendEvent(reactContext, afOnAppOpenAttribution, obj.toString());
          }
      } catch (JSONException e) {
          e.printStackTrace();
      }
  }
```

Maybe it needs to fix sendEvent's argument ( `afOnInstallConversionData` => `afOnInstallConversionDataLoaded` ) because it changed the code as the following at 1.4.5.

`index.js`

```diff
- const listener = NativeAppEventEmitter.addListener(
-   "onInstallConversionData",
+ const listener = appsFlyerEventEmitter.addListener(
+   "onInstallConversionDataLoaded",
```

https://github.com/AppsFlyerSDK/react-native-appsflyer/compare/v1.4.4...v1.4.5#diff-168726dbe96b3ce427e7fedce31bb0bcL161-R257

**Comment by pqkluan** [comment]
I confirmed the `onInstallConversionData` listener is working after applying the above changes.

This bug is also affecting the deferred deep-link feature on the Android since it based on `onInstallConversionData` event.

**Comment by haveamission** [comment]
I am still experiencing this bug in 5.0.0
