### ISSUE TITLE
Creating deep links no longer passes the URI params in iOS

### ISSUE THREAD

**Issue by vinnyhoward** [AppsFlyerSDK/react-native-appsflyer#114]
# Report

## Plugin Version

`1.4.5`

## On what Platform are you having the issue?

iOS/Android

## What did you do?

Creating deep links no longer passes the params in iOS

```
  generateGiftDeepLink: ({pendingId, setCopied, analyticsEvent}) => async () => {
      setCopied(true);
      Appsflyer.setAppInviteOneLinkID('aCHT', success => {
        analyticsEvent('Gift link copied');
        console.log(success);
      });

      Appsflyer.generateInviteLink(
        {
          '/something',
          campaign: 'myCampaign',
        },
        link => {
          Clipboard.setString(link);
        },
        err => {
          console.log(err);
        }
      );
    },
```

## What did you expect to happen?

I expected to see `exampleapp://something` but I only see `exampleapp://` in iOS, in Android I see the reverse which is just the params of `/something`.

## What happened instead?

There was a point where I would create and receive the entire deep link information after clicking on it but either the new AppsFlyer version or iOS 13 update affected these changes? I am not sure.

## Please provide any other relevant information.

I originally made a issue for this #99 where something similar happened, but was resolved.

**Comment by wesfieldj** [comment]
@vinnyhoward It seems that you are missing the 'channel' parameter in the json.

In the example above you have : 
```
       '/something',
          campaign: 'myCampaign',
```
So we would suggest adding the channel so it would look like: 


```
          channel:  '/something',
          campaign: 'myCampaign',
```
Here is the example from the docs:

```
appsFlyer.generateInviteLink(
 {
   channel: 'gmail',
   campaign: 'myCampaign',
   customerID: '1234',
   userParams: {
     myParam: 'newUser',
     anotherParam: 'fromWeb',
     amount: 1,
   },
 },
 (link) => {
   console.log(link);
 },
 (err) => {
   console.log(err);
 }
);
```

You can check out the docs here: https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/Docs/API.md#-appsflyergenerateinvitelinkargs-successc-errorc-void

**Comment by vinnyhoward** [comment]
@wesfieldj That didn't work, I'm started to think its something else. Will dig deeper and if something comes relevant to this repo I will create a new issue or reopen this one.
