### ISSUE TITLE
The same deeplink won't trigger the onAppOpenAttribution if the app is started and in background

### ISSUE THREAD

**Issue by rborn** [AppsFlyerSDK/react-native-appsflyer#119]
# Report

Hi everyone, I seem to have an issue on Android when I try to open the app using the same deeplink. 
This happens only on android and only when the app is in background (so not totally killed)
I added the details below

🤗

## Plugin Version

ℹ 1.4.6

## On what Platform are you having the issue?

ℹ android

## What did you do?

ℹ Install the plugin as per instructions, created a webpage that would have some deeplinks.

## What did you expect to happen?

ℹ I expect when clicking on any deeplink the app to fire `onAppOpenAttribution` (iOS works)

## What happened instead?

ℹ If I click on the same deeplink while the app is started but in background the app won't fire the `onAppOpenAttribution` event. The next sequence of operations are by just switching between app and chrome

- chrome -> deeplink_one -> app fires onAppOpenAttribution
- chrome -> deeplink_two -> app fires onAppOpenAttribution
- chrome -> deeplink_two -> app DOES NOT fire onAppOpenAttribution

It behaves like it would cache somehow the link, if I use the same deeplink but in long and short form it works

- chrome -> deeplink_one_short -> app fires onAppOpenAttribution
- chrome -> deeplink_one_short -> app DOES NOT fire onAppOpenAttribution
- chrome -> deeplink_one_long -> app fires onAppOpenAttribution
- chrome -> deeplink_one_long -> app DOES NOT fire onAppOpenAttribution

**Comment by wesfieldj** [comment]
@rborn can you check the debug logs for 'skipping re-use of previously consumed deep link'.

If you see this in the logs then this is the expected result. 

If you click the same link twice in the same sessions then onAppOpenAttribution will only be fired once.

This is the logic built into the SDK to prevent two re-target attributions in the same session.

If you want to get onAppOpenAttribution fired every time, then make sure to kill the app in-between deeplinks, or use two separate links.

**Comment by rborn** [comment]
@wesfieldj thanx for answering, I'll look for that log and come back.

But why is different on iOS, and what if the user goes back and forth between the linked page and the app? (imagine they receive an email with the link, the app opens, they navigate away from the linked page, they go back to email and click again on the same link)

🤗

**Comment by rborn** [comment]
update: yes I get that message

**Comment by wesfieldj** [comment]
@rborn The reason the behavior is different on iOS and Android is because of the way each sperate operating system handles deep linking.

It would be easier for everyone if they handled deep linking in the same way but unfortunately, that is not the case.

In iOS, we are able to handle deep links with the continue user activity method which will only be called once per link pressed.

In Android, the behavior is more tricky. The link data is attached to the intent, which is not changed in background foreground transitions. So this causes a scenario where one link can be attributed twice (in the same session), which will distort the data on your dashboard.

**Comment by rborn** [comment]
@wesfieldj thanks for explaining.

**Comment by idanlevi1** [comment]
> @rborn can you check the debug logs for 'skipping re-use of previously consumed deep link'.
> 
> If you see this in the logs then this is the expected result.
> 
> If you click the same link twice in the same sessions then onAppOpenAttribution will only be fired once.
> 
> This is the logic built into the SDK to prevent two re-target attributions in the same session.
> 
> If you want to get onAppOpenAttribution fired every time, then make sure to kill the app in-between deeplinks, or use two separate links.

If we use `Linking.addEventListener('url', this.handleOpenURL)` we can catch the deep link even if the app in the background, so it's not a good enough reason for this behavior in Android
