### ISSUE TITLE
Cannot compile on iOS

### ISSUE THREAD

**Issue by jsdario** [AppsFlyerSDK/react-native-appsflyer#12]
I have linked the library product on Build Phases as specified, and done this many times before with other libs, but I am unable to surpass the following:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AppsFlyerTracker", referenced from:
      objc-class-ref in RNAppsFlyer-BA59A0E70988396B.o
```

Everything seems to be working right. I just added the code needed to follow uninstalls per user.

**Comment by af-fess** [comment]
@jsdario hi, please give more details about your environment: `react-native` version and so on.

"Everything seems to be working right. I just added the code needed to follow uninstalls per user." did it work before 'uninstalls per user' feature?

**Comment by jsdario** [comment]
It was. But apparently I was missing the framework to be linked along the bridge library.
If it is required I could do a PR to add docs on how to link the framework for iOS.

**Comment by af-fess** [comment]
@jsdario go ahead, I will stay tuned

**Comment by sonnylazuardi** [comment]
I've got this too. Is there any update?

**Comment by af-fess** [comment]
@sonnylazuardi hi, I cannot reproduce this issue on my side so please give details about your env. what version of AppsFlyer do you use? Xcode version. can you post printscreen?

**Comment by sonnylazuardi** [comment]
@af-fess nevermind, solved by doing `pod install` first 🙇

**Comment by af-fess** [comment]
@sonnylazuardi BTW sometimes run `pod repo update` to fetch last versions of packages (not only related to Apssflyer)

**Comment by jsdario** [comment]
Thanks for the support, by the moment I believe the issue is more about troubleshooting than an issue itself. I'll try to make time to write a bit of docs. You may close the issue if you find it appropriate.

**Comment by af-fess** [comment]
@jsdario thank you
