### ISSUE TITLE
is_first_launch is boolean on iOS and string on Android

### ISSUE THREAD

**Issue by ptelad** [AppsFlyerSDK/react-native-appsflyer#122]
# Report

## Plugin Version

1.4.7

## On what Platform are you having the issue?

ios and android

## What did you do?

Ran the app

## What did you expect to happen?

In my code, I have a snippet kinda like this
```js
if (data.data.is_first_launch) {
 ...
}
```
You should enter the `if` only on first launch

## What happened instead?

On Android, we go inside the `if` every launch because the value of `data.data.is_first_launch` is `"false"`

## Please provide any other relevant information.

Here is the JSON on iOS:
```json
{
  "status": "success",
  "type": "onInstallConversionDataLoaded",
  "data": {
    "af_message": "organic install",
    "is_first_launch": false,
    "af_status": "Organic"
  }
}
```

and here it is on Android:
```json
{
  "status": "success",
  "type": "onInstallConversionDataLoaded",
  "data": {
    "af_status": "Organic",
    "af_message": "organic install",
    "is_first_launch": "false"
  }
}
```

**Comment by ptelad** [comment]
A work around for anyone who faces this issue is to wrap the property in `JSON.parse` like so:
```js
if (JSON.parse(data.data.is_first_launch)) {
 ...
}
```

This will ensure a boolean on both cases

**Comment by wesfieldj** [comment]
@ptelad We updated the docs to include your code, and we will make changes in the future to solve this issue. 
Thanks!
