### ISSUE TITLE
Google play warning update SDK version

### ISSUE THREAD

**Issue by JinYuSha0** [AppsFlyerSDK/react-native-appsflyer#124]
# Report

## Plugin Version
react-native 0.59.9
react-native-appsflyer 1.4.7

## On what Platform are you having the issue?
Android Google play

## What did you do?
npm install and manual link

## What did you expect to happen?
upgrade SDK

## What happened instead?
Received a Google play warning  to upgrade SDK

## Please provide any other relevant information.
![微信图片_20191206103608](https://user-images.githubusercontent.com/20939091/70291125-345b4d00-1815-11ea-861b-c69aaaf27110.jpg)

**Comment by wesfieldj** [comment]
@JinYuSha0 The AppsFlyer SDK in the latest version of the plugin is v4.10.2, so by installing the latest version, you will be complainant with the warning from Google.

**Comment by rborn** [comment]
@wesfieldj the latest version is 1.4.7 and it seems @JinYuSha0 has it installed, right?
I'm wondering if there is something more to do than just install the module? 🙂

**Comment by wesfieldj** [comment]
@rborn There is nothing else that needs to be done. Just install the latest version (1.4.7).

**Comment by JinYuSha0** [comment]
@rborn I just used initSdk and trackEvent APIs, and i already have the feature to collect IMEI, so i don't have to worry about anything?

**Comment by rborn** [comment]
@JinYuSha0 if you don't use AppsFlyer `setImeiData` it should be fine I think

**Comment by JinYuSha0** [comment]
@rborn @wesfieldj 
Thank you both!, close.
