### ISSUE TITLE
Switch to the Play Referrer API by March 1 2020

### ISSUE THREAD

**Issue by carloscuesta** [AppsFlyerSDK/react-native-appsflyer#127]
Hey 👋 

Google Playstore recently announced that the `install_referrer` is going to be deprecated on March 2020.

> ![Screenshot 2019-12-11 at 16 03 00](https://user-images.githubusercontent.com/7629661/70632772-c5745e80-1c2f-11ea-9659-3e09b364ea92.png)

I'm using the following version of AppsFlyer

`react-native-appsflyer": "^1.2.13`

Is this fixed on the last version ?

Thanks 🙏

**Comment by wesfieldj** [comment]
@carloscuesta the version you are using is fine. 

As you can see in v1.2.13 and later we already use the new google referrer play install referrer library -
https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/124cab649ee35f2d8cfb16e748af92b95e10c091/android/build.gradle#L32

So there is no need for action on your end.
