### ISSUE TITLE
Broadcast Receiver May Manually Have to Be Added

### ISSUE THREAD

**Issue by jackmaris** [AppsFlyerSDK/react-native-appsflyer#132]
# Report

## Plugin Version

1.4.7

## On what Platform are you having the issue?

Android

## What did you do?

Install the integration and run the non-organic install integration test

## What did you expect to happen?

The test would just work

## What happened instead?

We succeeded, but got a warning message along the lines of 'we couldn't track where the install came from. Please make sure you have Broadcast Receiver in AndroidManifest.xml'. 

Then, we manually added the following:
```xml
    <receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">
      <intent-filter>
      <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
      </receiver>
```

And tried the integration test again, and this time it worked with no warning message.

## Please provide any other relevant information.

We're on RN 0.61.3. We used autolinking.

**Comment by wesfieldj** [comment]
Historically there are two ways to collect the install_referer from google:

Using a broadcast receiver.
Using the new google play install referer library.
Only one of these methods needs to be implemented to get the install referrer from google.

Google is deprecating method (1).

For the last 2 years, AppsFlyer SDK is using method (2)

See - https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/android/build.gradle#L32

So as long as you have the latest version of the plugin there is no action required.

For more info see:
https://developer.android.com/google/play/installreferrer/library (new)
https://developers.google.com/android/reference/com/google/android/gms/tagmanager/InstallReferrerReceiver (old)

**Comment by wesfieldj** [comment]
Regarding the test app, the broadcast receiver is being deprecated by google in 3 months, so the app will be removed from the store soon. 

So please use the dashboard test, which can be found under `SDK integration tests` in the AppsFlyer dashboard.
