### ISSUE TITLE
Switch to play referrer API by march 1, 2020

### ISSUE THREAD

**Issue by TeamDlxx** [AppsFlyerSDK/react-native-appsflyer#133]
I received this email from google store

"Switch to play referrer API by march 1, 2020"

<img width="774" alt="Screenshot 2019-12-17 at 9 21 16 AM" src="https://user-images.githubusercontent.com/52232678/70964700-9b4af280-20ae-11ea-82ea-8b094f9724b4.png">

So I was looking in code and got to know that the issue is with App flyer. so please help me to understand the actual problem.

**Comment by wesfieldj** [comment]
Historically there are two ways to collect the install_referer from google:
1. Using a broadcast receiver.
2. Using the new google play install referer library. 

Only one of these methods needs to be implemented to get the install referrer from google. 

Google is deprecating method (1).

For the last 2 years, AppsFlyer SDK is using method (2)

See - https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/android/build.gradle#L32

So as long as you have the latest version of the plugin there is no action required.


For more info see: 
https://developer.android.com/google/play/installreferrer/library (new)
https://developers.google.com/android/reference/com/google/android/gms/tagmanager/InstallReferrerReceiver (old)

**Comment by nielskrijger** [comment]
Without the manifest it appears the SDK integration app doesn't run:

"AppsFlyer's BroadcastReceiver wasn't found in the Android manifest. It is required for the test to pass."

Not sure if everything else works, I assume it will (we haven't released yet).
