### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by rishabh876** [AppsFlyerSDK/react-native-appsflyer#138]
# Report 

> Fatal Exception: java.util.ConcurrentModificationException
>        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
>        at java.util.HashMap$EntryIterator.next(HashMap.java:891)
>        at java.util.HashMap$EntryIterator.next(HashMap.java:890)
>        at org.json.JSONObject.<init>(JSONObject.java:129)
>        at com.appsflyer.AppsFlyerProperties.saveProperties(AppsFlyerProperties.java:217)
>        at com.appsflyer.AppsFlyerLibCore.ˏ(AppsFlyerLibCore.java:1538)
>        at com.appsflyer.AppsFlyerLibCore.onHandleReferrer(AppsFlyerLibCore.java:50905)
>        at com.appsflyer.internal.i.onInstallReferrerSetupFinished(i.java:1069)
>        at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:7)
>        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1607)
>        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1635)
>        at android.os.Handler.handleCallback(Handler.java:836)
>        at android.os.Handler.dispatchMessage(Handler.java:103)
>        at android.os.Looper.loop(Looper.java:232)
>        at android.app.ActivityThread.main(ActivityThread.java:6661)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1106)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

## Plugin Version
`^5.0.0`

## On what Platform are you having the issue? 
android

## What did you do?
Found this on Production. No idea how this can be reproduced.

## What did you expect to happen?
To Not crash

## What happened instead?
The app crashed

## Please provide any other relevant information.
none

**Comment by wesfieldj** [comment]
@rishabh876 Thanks for reporting this issue.
We are aware of this crash and we released a fix for it in the lastest Android SDK.

So upgrading to react-native-appsflyer v5.1.0 (the latest version) should solve this issue for you.

Please let us know if you have any other questions.
