### ISSUE TITLE
can't get onInstallConversionData install data.

### ISSUE THREAD

**Issue by DevBkIL** [AppsFlyerSDK/react-native-appsflyer#17]
the callback of onInstallConversionData is not firing.
attribution work properly.

**Comment by DevBkIL** [comment]
Solution in case someone get this problem:
call onInstallConversionDataCanceller before initing the sdk...
save the conversion data in AsyncStorage and then use the data later..

`
import appsFlyer from 'react-native-appsflyer';

var onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
    (data) => {
      AsyncStorage.setItem('afdata',JSON.stringify(data));
      onInstallConversionDataCanceller&&onInstallConversionDataCanceller() ;   
    }
);

let options = { ...  };
appsFlyer.initSdk(options, cbSuccess, cbFail);
`

**Comment by DevBkIL** [comment]
RN 0.40, Android

**Comment by af-fess** [comment]
@DevBkIL yes, `onInstallConversionData` should be called before `initSdk`.
