### ISSUE TITLE
Play services dex error

### ISSUE THREAD

**Issue by Ehesp** [AppsFlyerSDK/react-native-appsflyer#2]
Hello,

I'm using this with other libs which also use play services. However since this lib forces 9.6.1 (https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/android/build.gradle#L28-L29) it won't install (Multiple dex files error). If I change the above lines to:

```
    compile 'com.google.android.gms:play-services-ads:+'
    compile 'com.google.android.gms:play-services-identity:+'
```

It works fine... Is it worth changing these to use the user preferred version?

**Comment by af-fess** [comment]
hi @Ehesp , yes, we thought about that feature when ran `demo` example. In the future we will provide CLI promt to let to user to choose if he want to add these dependancies. On other hand we can make it optional and user can set it manually.

**Comment by af-fess** [comment]
we added dependency as:

```
compile 'com.google.android.gms:play-services-ads:9.6.+'
compile 'com.google.android.gms:play-services-identity:9.6.+'
```

**Comment by Ehesp** [comment]
Cheers!

**Comment by Ehesp** [comment]
@af-fess Any chance you could deploy a minor version on npm for this?

**Comment by af-fess** [comment]
@Ehesp hi, we work on this, there are some `Pod` dependancies  that causes to issues.
