### ISSUE TITLE
initSdk undefined/can't link

### ISSUE THREAD

**Issue by brunocramos** [AppsFlyerSDK/react-native-appsflyer#3]
Hi,
I've successfully installed AppsFlyer pod and npm package, but I keep getting this when running react-native link:
`rnpm-install ERR! It seems something went wrong while linking. Error: Expected "{" but "/" found. `

For now, without linking, I'm unable to initialize the sdk. First, I get this:
![image](https://cloud.githubusercontent.com/assets/4956907/20608384/a6f59660-b268-11e6-888e-aaaa0bc2ad1c.png)

And then, if I try to track any event, this:
![image](https://cloud.githubusercontent.com/assets/4956907/20608396/bc1f9914-b268-11e6-9ab5-ff34a1728660.png)

Is there any step missing in the readme? How should I proceed?

**Comment by af-fess** [comment]
please provide more details, versions, what did you run? Try to  clone the repo and run `react-native link` under `demo/` project

**Comment by thomasMary** [comment]
Running into the same issue:
- `yarn add react-native-appsflyer`
- Add the `appsFlyerFramework` to podfile
- `pod install`
- rebuild

Using AppsFlyerFramework (4.5.12)
React native 0.37.0
xCode  8.1

**Comment by iuraya** [comment]
I'm also running the same problem.

We've followed the instructions to integrate de module as marked in the guide.

The problem occurs while initializing the sdk:
<img width="386" alt="captura de pantalla 2016-12-16 a las 13 17 52" src="https://cloud.githubusercontent.com/assets/14769734/21262553/3458620a-c392-11e6-8de5-15b4870c80df.png">

While debbugin the index.js of the module the 'eventsMap' has not been initialized

Our project specifications

- Appsflyer: 4.5.12
- React-native: 0.33.0
- xCode: 8.1

**Comment by af-fess** [comment]
hi, can anyone to clone this repo and run `demo` project?  just run from root `npm run preparedemo`. I have `react-native 0.36.1` and cannot reproduce, continue to dig

**Comment by af-fess** [comment]
@iuraya I succeeded to reporduce it on `demo`, we work on it, thanks

**Comment by jpradamartin** [comment]
Hi @af-fess, with the additional step, it appears other error:
![simulator screen shot 17 dic 2016 17 48 55](https://cloud.githubusercontent.com/assets/3111096/21288511/4a83a2bc-c485-11e6-8bd1-075cc448edb4.png)



and about the demo, into package.json, it appears the next row:
"react-native-appsflyer": "file:///Users/maxim/Appsflyer/projects/react-native-appsflyer"
As you can see,  the path is your private path(is a different context).

Thanks!

**Comment by af-fess** [comment]
@jpradamartin hey, about demo - its ok, when you run `npm run preparedemo` it installes plugin from your cloned repo.  About error you mentioned above: how did you implement `initSdk` method? please post the code snippets. Looks like you didn't implement error callback. please see `demo` -> `index.ios.js`. You also can open issue/request to set error callback as optional. Thanks

**Comment by af-fess** [comment]
added step to README
