### ISSUE TITLE
Update iOS and Android SDKs to comply with GDPR

### ISSUE THREAD

**Issue by fluiddot** [AppsFlyerSDK/react-native-appsflyer#42]
I received an email from Appsflyer telling me to update the iOS and Android SDKs but seems like the integration with react native is not updated, please update it as soon as possible.

Thanks!

**Comment by af-fess** [comment]
added API to 1.2.9 `stopTracking`: https://github.com/AppsFlyerSDK/react-native-appsflyer#stopTracking
