### ISSUE TITLE
Unique Users didn't Count on trackEvent

### ISSUE THREAD

**Issue by ghost** [AppsFlyerSDK/react-native-appsflyer#45]
i have track the event like this :
```
appsFlyer.trackEvent("Search", {},
            (result) => {
                console.log(result);
            },
            (error) => {
                console.error(error);
            }
        )

```
And the event already recorded in appsflyer dashboard, but the unique users didn't count.
is there anything should i add in the code to handle that?

![screen shot 2018-06-05 at 11 16 56](https://user-images.githubusercontent.com/11230105/40955457-66c0b120-68b4-11e8-83ef-c8bd724bf2d9.png)

**Comment by imkamalh** [comment]
Oh well, this happens to me too ;)

**Comment by af-fess** [comment]
Seems like a question for [support](support@appsflyer.com). 
We are counting unique users for organic and non-organic in-apps. 
For organic we will not count for reinstalls and for in-app events that were sent before the install
