### ISSUE TITLE
Unable to see any Non-Organic installs 

### ISSUE THREAD

**Issue by krunalFlexiLoans** [AppsFlyerSDK/react-native-appsflyer#46]
Hi,

Have integrated SDK, made the app on appsflyer, and have tried it with 9Apps Channel for non-organic installs, but unable to see any of them.

Please help

**Comment by chris-feist** [comment]
It appears like the react-native SDK does not include the [Broadcast receiver](https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android#25-setting-the-broadcastreceiver-in-androidmanifestxml) needed to track this.

The broadcast receiver should be in the libraries manifest by default, so react native developers don't have to manually add it. At the very least, it should be included in this repo's documentation on how to hook it up manually if its not included.

```
<receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">
    <intent-filter>
         <action android:name="com.android.vending.INSTALL_REFERRER" />
     </intent-filter>
</receiver>
```

**Comment by af-fess** [comment]
Hi @chris-feist, the react-native plugin uses [Google install referrer ] by default (https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/android/build.gradle#L32)

So you don't need to implement `com.android.vending.INSTALL_REFERRER` receiver.
