### ISSUE TITLE
trackEvent crashes when empty properties passed

### ISSUE THREAD

**Issue by alexxv** [AppsFlyerSDK/react-native-appsflyer#5]
Hey, 

When calling `AppsFlyer.trackEvent('login')` or `AppsFlyer.trackEvent('login', {})` it fails with NPE.
In order to make it work, the `properties` have to contain at least one value.

Alex

**Comment by af-fess** [comment]
@alexxv hi Alex, yes SDK handles empty values for event. Its plugin bug, happens on both A/I. will be fixed

**Comment by af-fess** [comment]
fix done in 1.0.8
