### ISSUE TITLE
iOS Pod file requires manual link to React pod in node_modules

### ISSUE THREAD

**Issue by chris-feist** [AppsFlyerSDK/react-native-appsflyer#50]
After following your iOS install directions. I kept getting a warning when installing the pod: `[!] React has been deprecated`. This also led to build issues in the React Native packager:
```
Ambiguous resolution: module ".../index.js" tries to require 'react-native', but there are several files providing this module. You can delete or fix them:

.../MyProject/ios/Pods/React/package.json

.../MyProject/node_modules/react-native/package.json
```

I got around the issue by manually linking the `React` pod to the `node_modules` directory so that it wasn't downloaded by the AppsFlyer pod.
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport'
]
pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'

post_install do |installer|
   installer.pods_project.targets.each do |target|
      # It also wouldn't work without this
      if target.name == "React"
        target.remove_from_project
      end
   end
end
```

Do you guys need the React dependency in the podspec file given that this already is a react native project?

**Comment by vovkasm** [comment]
_note_: I'm a user of appsflyer, but can explain this.

Recent cocoapods don't add something into pod include paths if it not a dependency of pod. So it is required specify `React` as dependency in `react-native-appsflyer.podspec`.

Most working pods for react-native follow this pattern ([firebase](https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase.podspec#L18), [react-native-navigation](https://github.com/wix/react-native-navigation/blob/v2/ReactNativeNavigation.podspec#L21), [sentry](https://github.com/getsentry/react-native-sentry/blob/master/SentryReactNative.podspec#L20) etc...)

I'd personally recommend to use cocoapods for all deps including react-native, it simplifies maintenance of project for ios.
