### ISSUE TITLE
Android now requires ACCESS_WIFI_STATE permission

### ISSUE THREAD

**Issue by chris-feist** [AppsFlyerSDK/react-native-appsflyer#51]
I integrated the React Native SDK into my app and now our Android app requires an additional permission to read "Wi-Fi Connection information" since your library adds the `android.permission.ACCESS_WIFI_STATE` to our final manifest.

Why is this permission needed and automatically included?

**Comment by af-fess** [comment]
hi @chris-feist, Generally  we need `android.permission.INTERNET` to run basic SDK logic. Take a look on this [README](https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android#24-setting-the-required-permissions)

>Why is this permission needed and automatically included?"

Generally if SDK for some reason will fail to collect advertiser ID, it will generate fingerprint for proper attribution based on Network and Wifi state

**Comment by chris-feist** [comment]
@af-fess there is nothing like that in the README you linked, nor is it covered in the Android unique ID documentation; unless you are using a hardware identifier which should be **avoided**.

https://developer.android.com/training/articles/user-data-ids
https://support.google.com/googleplay/android-developer/answer/6048248?hl=en

Please provide a link to some valid documentation or bug that describes otherwise. For now, we'll opt to remove that permission from our merged manifest by adding the following line to our app manifest:
```
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" tools:node="remove" />
```
