### ISSUE TITLE
Android SDK Integration Test app fails 

### ISSUE THREAD

**Issue by willbt** [AppsFlyerSDK/react-native-appsflyer#52]
I'm consistently getting failures in the Android SDK integration test 

![img_0016](https://user-images.githubusercontent.com/372302/46280408-684a3b00-c59e-11e8-9e6e-fdc30a444482.JPG)

1. I'm using version v1.2.13 (latest)
2. BroadcasterReceiver is configured correctly
3. This point is not relevant to react-native apps and there is no documentation to suggest this is required.

@af-fess can you please help?

**Comment by willbt** [comment]
I can also see in the AppsFlyer Overview screen that the AppsFlyer_Test media source is being tracked 
<img width="1030" alt="screen shot 2018-10-01 at 17 52 55" src="https://user-images.githubusercontent.com/372302/46282012-ff18f680-c5a2-11e8-933b-3378b7044ad7.png">

**Comment by af-fess** [comment]
Hi @willbt Do you run the test on Android O? if so , we have issue with this OS and will be fixed shortly.

**Comment by gschier** [comment]
I'm getting the same error on Android 9.0 in the Emulator.

I added the BroadcastReceiver definition to `Manifest.xml` like the error said but that didn't seem to help.

**Comment by gschier** [comment]
Set up the Android 7.0 emulator and seems to be working for now
