### ISSUE TITLE
Where is android methods in this wrapper?

### ISSUE THREAD

**Issue by iagorm** [AppsFlyerSDK/react-native-appsflyer#56]
Checking the code to integrate the wrapper to SDK, I saw that there is almost nothing for the android:

```JS
/**
 * iOS only
 */

appsFlyer.trackAppLaunch = () => {
    return RNAppsFlyer.trackAppLaunch();
}

appsFlyer.trackLocation = (longitude, latitude, callback) => {
    return RNAppsFlyer.trackLocation(longitude, latitude, callback);
};

appsFlyer.trackEvent = (eventName, eventValues, successC, errorC) => {
    return RNAppsFlyer.trackEvent(eventName, eventValues, successC, errorC);
};

appsFlyer.setUserEmails = (options, successC, errorC) => {
    return RNAppsFlyer.setUserEmails(options, successC, errorC);
};

appsFlyer.getAppsFlyerUID = (callback) => {
    return RNAppsFlyer.getAppsFlyerUID(callback);
};

appsFlyer.sendDeepLinkData = (callback) => {
    return RNAppsFlyer.sendDeepLinkData(callback);
};
```

How can I track events, app installs/uninstalls, etc.. in android?

Also when I try to track a Event I receive this:

![screenshot_1541784639](https://user-images.githubusercontent.com/13892132/48278365-6cd30080-e434-11e8-8e66-52ece7d5f930.png)

**Comment by iagorm** [comment]
Was my fault the method was thrown error:

It must receive all parameters in order to work properly:

```JS
appsFlyer.trackEvent(eventName, eventValues,
(result) => {
console.log(result);
},
(error) => {
console.error(error);
}
```

**Comment by af-fess** [comment]
@iagorm good to hear, anyways, we will add another signature of empty event without `eventValues` to get rid of this situation

Cheers,

**Comment by iagorm** [comment]
@af-fess A good solution for this is to create an interface file to allow the developer when typing the method, to check the parameters and its type values, making the library more friendly.
