### ISSUE TITLE
Error on calling trackEvent

### ISSUE THREAD

**Issue by iadcg** [AppsFlyerSDK/react-native-appsflyer#59]
After initializing the sdk, call like this

```
const eventValues = {
	af_content_id: 'id123',
	af_currency: 'USD',
	af_revenue: '2',
};
appsFlyer.trackEvent('af_add_to_cart', eventValues);
```

Then it will throw error
![whatsapp image 2018-12-06 at 5 07 41 pm](https://user-images.githubusercontent.com/45412363/49573762-bf430680-f979-11e8-83ec-3b206d1a9df4.jpeg)

**Comment by af-fess** [comment]
hi @iadcg you miss callbacks or put `null`s. See the example: https://github.com/AppsFlyerSDK/react-native-appsflyer#-appsflyertrackeventeventname-eventvalues-successc-errorc-void

In next release we will set new signature `appsFlyer.trackEvent('af_add_to_cart', eventValues);`
