### ISSUE TITLE
Android SDK Integration Test fails

### ISSUE THREAD

**Issue by sorokin0andrey** [AppsFlyerSDK/react-native-appsflyer#63]
Android 8.0. Im tried to update dependence com.appsflyer:af-android-sdk:4.8.14@aar to 4.8.18 and 4.8.19 but nothing happened.
![photo_2019-01-11_19-02-02 1](https://user-images.githubusercontent.com/3092044/51393296-681f7c80-1b48-11e9-823e-805a7aee3ae4.jpg)

**Comment by dev-z** [comment]
Same case here. The startTracking() and non-organic install verified tests are not passing on Android.
I'm using react-native-appsflyer versionn 1.4.2

![Screenshot_2019-04-17-18-02-08-062_com appsflyer referrerSender_masked](https://user-images.githubusercontent.com/8604312/56342632-27321500-61d6-11e9-82a9-68f23c77cc63.png)

**Comment by ameanshinobu** [comment]
I solved this issue by adding permission and receiver in AndroidManifest.xml as follow:

**Permission**:
`<uses-permission android:name="android.permission.INTERNET" />`
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`
`<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />`

**Receiver**:
`<receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">`
`	<intent-filter>`
`	    <action android:name="com.android.vending.INSTALL_REFERRER" />`
`	</intent-filter>`
`</receiver>`

Reference: https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android
