### ISSUE TITLE
use_frameworks! doesnt work 

### ISSUE THREAD

**Issue by yoginair** [AppsFlyerSDK/react-native-appsflyer#64]
[!] The 'Pods-mobileappb2c' target has transitive dependencies that include static binaries: (/Users/yogi/Documents/app/ios/Pods/AppsFlyerFramework/AppsFlyerLib.framework)

**Comment by af-fess** [comment]
@yoginair new version of pod already supports static framework

**Comment by gsunsnackv** [comment]
@af-fess Your podspec does not have `s.static_framework = true`
https://github.com/CocoaPods/CocoaPods/issues/7234

I'm experiencing this error as well

**Comment by dkwl93** [comment]
Any update on this issue?

**Comment by af-fess** [comment]
will be fixed on Sunday (28 July) @wesfieldj FYI

**Comment by wesfieldj** [comment]
The latest version v1.1.4 contains s.static_framework = true
