### ISSUE TITLE
Building error on v1.3.2

### ISSUE THREAD

**Issue by GoshaEgorian** [AppsFlyerSDK/react-native-appsflyer#66]
### Error message
```console
Task :app:compileDebugJavaWithJavac FAILED
path-to-project/android/app/src/main/java/com/**/**/MainApplication.java:67: error: constructor RNAppsFlyerPackage in class RNAppsFlyerPackage cannot be applied to given types;
            new RNAppsFlyerPackage(MainApplication.this),
            ^
  required: no arguments
  found: MainApplication
  reason: actual and formal argument lists differ in length
Note: path-to-project/android/app/src/main/java/com/**/**/MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```
### Error version
Upgrade from 1.3.1 to 1.3.2

**Comment by af-fess** [comment]
@GoshaEgorian yes, we decided to remove `Application` argument that should solve problem with `link`, see https://github.com/AppsFlyerSDK/react-native-appsflyer/commit/1786336a393af814066f7f8174b9633e9081a844#diff-ae61ed9a00665119f8ef0acf14b61a07L41

For old versions `$ react-native link` command adds contractor `new RNAppsFlyerPackage()` and do not removes `new RNAppsFlyerPackage(MainApplication.this)`.

**Comment by aposhettigar** [comment]
i have this same issue with AppsFlyer v6.0.30, 

unlinking and linking didn't help me either

**Comment by af-fess** [comment]
hi @aposhettigar, do you able to import `RNAppsFlyerPackage` manually inside `ReactApplication` class?

`RNAppsFlyerPackage` constructor has no arguments. https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerPackage.java#L16-L17

From which version you want to upgrade the AppsFlyer plugin?
