### ISSUE TITLE
Missing Organic/Non-organic Users

### ISSUE THREAD

**Issue by santiph** [AppsFlyerSDK/react-native-appsflyer#68]
There are other issues reported, but were closed without a proper solution.
As for today, using the latest available version `1.3.2` we're unable to get most of our users reported as Users in AppsFlyer on Android devices, regardless if SDK Integration Test is used or not. Whitelisted or not. Simulators or real devices.
This used to work fine on iOS.

Our approach for the moment is to implement Java/Android SDK and write our own Native Module to consume from Javascript (Basically, our own version of `react-native-appsflyer`)

**Comment by af-fess** [comment]
@santiph can you provide more details for this problem?
Last week we released `1.4.1` with the fix on Android side + separation of `getConversionData` and `onAppOpenAttribution` callbacks
