### ISSUE TITLE
setGCMProjectID is not a function

### ISSUE THREAD

**Issue by WASHSWATDAVID** [AppsFlyerSDK/react-native-appsflyer#70]
Hi. I got these message. what happen?

`Possible Unhandled Promise Rejection (id: 0):
TypeError: _reactNativeAppsflyer.default.setGCMProjectID is not a function
TypeError: _reactNativeAppsflyer.default.setGCMProjectID is not a function`

Here's my Code

```
componentDidMount = async() => {
  let fcmToken = await getValue(Keys.TOKEN);
  if (!fcmToken) {
    fcmToken = await firebase.messaging().getToken();
    if (fcmToken) {
      setValue(Keys.TOKEN, fcmToken);
      ChannelIO.initPushToken(fcmToken);
      appsFlyer.setGCMProjectID(fcmToken,
        (gcmProjectID) => {
        },
        (error) => {
        })
    }
  }
}
```

**Comment by af-fess** [comment]
@WASHSWATDAVID the `appsflyer` plugin doesn't have such a method `setGCMProjectID`. Please read README: https://github.com/AppsFlyerSDK/react-native-appsflyer#-android-1

**Comment by jasonivers** [comment]
It's in the documentation from the [support site](https://support.appsflyer.com/hc/en-us/articles/217108646-React-Native-plugin).  Having differing documentation is confusing... any chance you can get them to both be accurate?
