### ISSUE TITLE
uninstall tracking not working

### ISSUE THREAD

**Issue by t0m0120** [AppsFlyerSDK/react-native-appsflyer#77]
Hi !
I tried implementing the uninstall tracking by reading the README but can't check it with the test flight.
Is there any mistake in this method?

version
```
react-native-appsflyer: 1.4.1
react-native: 0.57.8
```

appdelegate.m
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [[AppsFlyerTracker sharedTracker] registerUninstall:deviceToken];
}
```

**Comment by namaxinan** [comment]
same issues here

**Comment by af-fess** [comment]
hey @t0m0120 , did you provide `p12` file to AppsFlyer dashboard?
Also in debug mode, do you able to see that `[[AppsFlyerTracker sharedTracker] registerUninstall:deviceToken];` is called with token?

**Comment by t0m0120** [comment]
@af-fess 
Thank you for your early reply!
The p12 file is set to AppsFlyer.

I tried debugging
app_id and token seem to be taken.

```
 [DEBUG] AppsFlyer: -[AppsFlyerTracker backgroundRegisterUninstall:] 
calling register Uninstall: https://register.appsflyer.com/api/v4.9/iosevent?buildnumber=4.8.12&app_id=APP_ID (with token: TOKEN)
```

```
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
<~+~   SEND Register-Uninstall: https://register.appsflyer.com/api/v4.9/iosevent?buildnumber=4.8.12&app_id=XXXXXX
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
{
	"useDevelopment": false,
	"uid": "XXXX-XXX",
	"advertiserId": "XXXXX",
	"OriginalAppsFlyerId": "XXXXX",
	"sdk_version": "4.8.12",
	"launch_counter": "4",
	"bundlename": "APPNAME",
	"devkey": "XXXXXXXXX",
	"bundleversion": "2",
	"topic": "app.bundleid",
	"wifi": "true",
	"reInstallCounter": 61,
	"devicetoken": "XXXXXX",
	"deviceData": {
		"cpu_type": "ARM64_V8",
		"cpu_speed": "-1",
		"osVersion": "12.1.4 (Build 16D57)",
		"ram_size": "2002",
		"cpu_64bits": "true",
		"device_model": "iPhone9,1",
		"cpu_count": "2"
	},
	"appUID": "",
	"install_date": "2019-03-07_183206+0900",
	"shortbundleversion": "1.0.1",
	"vendorId": "XXXXXXX"
}
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
```

**Comment by namaxinan** [comment]
I never get this log `[DEBUG] AppsFlyer: -[AppsFlyerTracker backgroundRegisterUninstall:] `
Is `[[AppsFlyerTracker sharedTracker] registerUninstall:deviceToken];` enough to enable it ?

**Comment by af-fess** [comment]
@namaxinan if you don't see this log, means you didn't get `deviceToken`. Worth to check again id Push notification works properly

**Comment by ragozin-n** [comment]
Same here, but on Android. Integrate SDK according to [this doc.](https://support.appsflyer.com/hc/en-us/articles/208004986-Android-Uninstall-Tracking)

```javascript
 "react-native-appsflyer": "^1.4.2",
 "react-native": "0.57.8"
```

**Comment by ragozin-n** [comment]
Use
```javascript
appsFlyer.enableUninstallTracking(PROJECT_FCM_KEY (short one), result =>
        store.dispatch({ type: AF_UNINSTALL_TRACKING_STATUS, payload: {}, status: result, error: '' })
      )
```

Result always success, but no info in dashboard. In dashboard we use long key, firebase server key I guess.

**Comment by CapitanRedBeard** [comment]
@ragozin-n 	Did you're above comment work for you? We have 2 FCM server keys both at 152 char limit. Did you just try both until one worked? Or did you make a new one just for uninstalls?

**Comment by ragozin-n** [comment]
> @ragozin-n Did you're above comment work for you? We have 2 FCM server keys both at 152 char limit. Did you just try both until one worked? Or did you make a new one just for uninstalls?

We use separate "uninstall" firebase project and replace that key according to env

**Comment by tiagobnobrega** [comment]
Thi is also not working for my project. I use FCM for push notifications also. I looked at the instructions at: [Android Unistall](https://support.appsflyer.com/hc/en-us/articles/210289286#Android-Uninstall), but this is for Android Sdk.  The doc states a custom FirebaseMessagingService should be used. Not sure if this affects anything, in this case. Should I import the lib as if it's android native app and ignore the RN wrapper for uninstall tracking ?

**Comment by sangupandi** [comment]
> Use
> 
> ```js
> appsFlyer.enableUninstallTracking(PROJECT_FCM_KEY (short one), result =>
>         store.dispatch({ type: AF_UNINSTALL_TRACKING_STATUS, payload: {}, status: result, error: '' })
>       )
> ```
> 
> Result always success, but no info in dashboard. In dashboard we use long key, firebase server key I guess.

Same Issue.. How to resolve this :(
