### ISSUE TITLE
Can not set custom params while generating onelink using generateInviteLink method.

### ISSUE THREAD

**Issue by codesinghanoop** [AppsFlyerSDK/react-native-appsflyer#78]
static generateInviteLink () {
    var inviteOptions = {
      channel: 'gmail',
      campaign: 'myCampaign',
      customerID: '1234',
      userParams: {
        myParam: 'newUser',
        anotherParam: 'fromWeb',
        amount: 1
      }
    }
    var onInviteLinkSuccess = function (link) {
      console.log('the appsflyer link is', link) // Handle Generated Link Here
    }
    function onInviteLinkError (err) {
      console.log(err)
    }
    AppsFlyer.generateInviteLink(
      inviteOptions,
      onInviteLinkSuccess,
      onInviteLinkError
    )
  }

when i use oninstallconversiondata function to get install conversion data then i don't receive custom params. Any help would be appreciated. Thanks in advance.

**Comment by vinnyhoward** [comment]
Any updates?

**Comment by wesfieldj** [comment]
This issue was fixed. 
See - https://github.com/AppsFlyerSDK/react-native-appsflyer/commit/789dd38178472a03c0e3d2f8b470d7945d960d3d

Thanks for your help!
