### ISSUE TITLE
customerId is not sent to PUSH API

### ISSUE THREAD

**Issue by alexxv** [AppsFlyerSDK/react-native-appsflyer#8]
Hey, 

I'm setting `customerId` in my app, but when our server side receives a PUSH call, with installation details it does not contain the `customerId` I set.

Thanks

**Comment by af-fess** [comment]
@alexxv did you see defined  `customerId` sent from SDK?

**Comment by alexxv** [comment]
@af-fess yes, in a `trackEvent` called after I've set it

**Comment by af-fess** [comment]
@alexxv yes, for today we don't send this value with row data but ticket is opened. Thanks,
