### ISSUE TITLE
[Android] onInstallConversionDataLoaded callback always return organic result

### ISSUE THREAD

**Issue by pqkluan** [AppsFlyerSDK/react-native-appsflyer#88]
**What I'm trying to do**
I tried to get the convention data (deferred deep linking) via `onInstallConversionData` callback

**What I've done**
- Click the following Onelink: 
```
// Short version
https://eatsy.onelink.me/sEgl/dailydeals

// Long version
https://eatsy.onelink.me/sEgl?pid=dailydeals&is_retargeting=true&af_dp=eatsy%3A%2F%2Fhighlight-details%3FhighlightID%3D6
```

- Got re-directed to the Google Play Store
- Install the app using `adb install` command
- Open the app

**Expected result**
`onInstallConversionData` called with the non-organic result (pid=dailydeals), af_dp=`eatsy://highlight-details?highlightID=6`

**Actual result**
`onInstallConversionData ` called with the following data: `{"af_status":"Organic","af_message":"organic install","is_first_launch":"true"}`

Screenshot wit the pid and af_status highlighted:
<img width="1288" alt="appslfyer-bug" src="https://user-images.githubusercontent.com/12025966/58926670-32390880-8776-11e9-802b-24a31096c202.png">

Full logcat of the application with "AppsFlyer" filter:
```
com.eatsy D/AppsFlyer: Starting Tracking
com.eatsy D/AppsFlyer_4.9.0: Install referrer is allowed
com.eatsy D/AppsFlyer_4.9.0: Initializing AppsFlyer SDK: (v4.9.0.184)
com.eatsy D/AppsFlyer_4.9.0: InstallReferrer connected
com.eatsy I/AppsFlyer_4.9.0: Sending first launch for this session!
com.eatsy I/AppsFlyer_4.9.0: Starting AppsFlyer Tracking: (v4.9.0.184)
com.eatsy I/AppsFlyer_4.9.0: Build Number: 184
com.eatsy I/AppsFlyer_4.9.0: sendTrackingWithEvent from activity: com.eatsy.MainApplication
com.eatsy I/AppsFlyer_4.9.0: Trying to fetch GAID..
com.eatsy I/AppsFlyer_4.9.0: onBecameForeground
com.eatsy I/AppsFlyer_4.9.0: Last Launch attempt: 2019/06/05 02:00:59.064 +0000;
    Last successful Launch event: 1969/12/31 23:59:59.999 +0000;
    This launch is blocked: 224 ms < 5000 ms
com.eatsy I/AppsFlyer_4.9.0: sendTrackingWithEvent from activity: com.eatsy.MainApplication
com.eatsy I/AppsFlyer_4.9.0: Trying to fetch GAID..
com.eatsy I/AppsFlyer_4.9.0: ******* sendTrackingWithEvent: Launch
com.eatsy I/AppsFlyer_4.9.0: Initialising KeyStore..
com.eatsy I/AppsFlyer_4.9.0: Creating a new key with alias: com.appsflyer,KSAppsFlyerId=1559700059471-6851905248027335411,KSAppsFlyerRICounter=0
com.eatsy I/AppsFlyer_4.9.0: ******* sendTrackingWithEvent: AND_Open_First
com.eatsy I/AppsFlyer_4.9.0: IMEI was not collected.
com.eatsy I/AppsFlyer_4.9.0: Android ID was not collected.
com.eatsy D/AppsFlyer_4.9.0: AppsFlyer: first launch detected
com.eatsy I/AppsFlyer_4.9.0: AppsFlyer: first launch date: 2019-06-05_020059+0000
com.eatsy D/AppsFlyer_4.9.0: didConfigureTokenRefreshService=true
com.eatsy I/AppsFlyer_4.9.0: AppsFlyerLib.sendTrackingWithEvent
com.eatsy I/AppsFlyer_4.9.0: url: https://events.appsflyer.com/api/v4/androidevent?buildnumber=4.9.0&app_id=com.eatsy
com.eatsy I/AppsFlyer_4.9.0: data: {"country":"US","af_timestamp":"1559700059509","appsflyerKey":"S********************P","af_events_api":"1","isFirstCall":"true","registeredUninstall":false,"operator":"Mobifone","network":"WIFI","af_v2":"bea1cef758c897dc7c550a9f230e996c2120d401","uid":"1559700059471-6851905248027335411","eventValue":"{}","isGaidWithGps":"true","lang_code":"en","installDate":"2019-06-05_020036+0000","app_version_code":"50","firstLaunchDate":"2019-06-05_020059+0000","ivc":false,"eventName":"AND_Open_First","model":"F5122","lang":"English","brand":"Sony","deviceType":"user","product":"F5122","deviceData":{"cpu_abi":"arm64-v8a","build_display_id":"34.4.A.2.118","dim":{"size":"2","ydp":"443.345","xdp":"449.704","y_px":"1776","x_px":"1080","d_dpi":"480"},"arch":"","cpu_abi2":""},"date2":"2019-06-05_020036+0000","counter":"0","date1":"2019-06-05_020036+0000","advertiserId":"33fea9dd-067f-4291-bccf-34cb76d35cc7","advertiserIdEnabled":"true","af_v":"14b9c091abbbaac0bd524a93336454ee2e759991","carrier":"","af_preinstalled":"false","iaecounter":"1","kef5869":"535c4f662eecb8c44818191c0c531a0d591f1e0d5a1812","sdk":"26","app_version_name":"2.5.0","device":"F5122","platformextension":"android_reactNative","cksm_v1":"893d98237a38e135efb3c643780daf3f02"}
com.eatsy I/AppsFlyer_4.9.0: response code: 200
com.eatsy I/AppsFlyer_4.9.0: IMEI was not collected.
com.eatsy I/AppsFlyer_4.9.0: Android ID was not collected.
com.eatsy I/AppsFlyer_4.9.0: AppsFlyer: first launch date: 2019-06-05_020059+0000
com.eatsy D/AppsFlyer_4.9.0: didConfigureTokenRefreshService=true
com.eatsy I/AppsFlyer_4.9.0: AppsFlyerLib.sendTrackingWithEvent
com.eatsy D/AppsFlyer_4.9.0: Install referrer is allowed
com.eatsy I/AppsFlyer_4.9.0: url: https://t.appsflyer.com/api/v4/androidevent?buildnumber=4.9.0&app_id=com.eatsy
com.eatsy I/AppsFlyer_4.9.0: data: {"country":"US","af_timestamp":"1559700059371","appsflyerKey":"S********************P","af_events_api":"1","isFirstCall":"false","registeredUninstall":false,"operator":"Mobifone","network":"WIFI","timepassedsincelastlaunch":"-1","open_referrer":"","af_v2":"b4cbeee5f0c00564e2260acc4a2aaf5962356e20","uid":"1559700059471-6851905248027335411","isGaidWithGps":"true","lang_code":"en","installDate":"2019-06-05_020036+0000","app_version_code":"50","firstLaunchDate":"2019-06-05_020059+0000","ivc":false,"model":"F5122","lang":"English","kef506e":"5de26051346b67214818191c0c531a0d591f1e0d5a1f1a","brand":"Sony","batteryLevel":"86.0","deviceType":"user","product":"F5122","deviceData":{"sensors":[{"sT":1,"sVS":[0.11013794,0.13526917,9.509171],"sN":"BMI160 Accelerometer","sV":"BOSCH","sVE":[0.13887024,0.120895386,9.64563]},{"sT":2,"sVS":[-7.949829,26.400757,-49.20044],"sN":"AK09915 Magnetometer -Wakeup Secondary","sV":"AKM","sVE":[-20.700073,31.64978,-50.549316]},{"sT":4,"sVS":[-0.004714966,0.0082092285,3.8146973E-4],"sN":"BMI160 Gyroscope","sV":"BOSCH","sVE":[0.0037994385,-0.0013885498,0.020614624]},{"sT":2,"sVS":[-7.949829,26.400757,-49.20044],"sN":"AK09915 Magnetometer","sV":"AKM","sVE":[-20.700073,31.64978,-50.549316]},{"sT":1,"sVS":[0.11013794,0.13526917,9.509171],"sN":"BMI160 Accelerometer -Wakeup Secondary","sV":"BOSCH","sVE":[0.13887024,0.120895386,9.64563]},{"sT":4,"sVS":[-0.004714966,0.0082092285,3.8146973E-4],"sN":"BMI160 Gyroscope -Wakeup Secondary","sV":"BOSCH","sVE":[0.0037994385,-0.0013885498,0.020614624]}],"cpu_abi":"arm64-v8a","build_display_id":"34.4.A.2.118","btch":"usb","dim":{"size":"2","ydp":"443.345","xdp":"449.704","y_px":"1776","x_px":"1080","d_dpi":"480"},"arch":"","btl":"86.0","cpu_abi2":""},"date2":"2019-06-05_020036+0000","counter":"1","date1":"2019-06-05_020036+0000","advertiserId":"33fea9dd-067f-4291-bccf-34cb76d35cc7","advertiserIdEnabled":"true","af_v":"59ad326f811ec887009ff75a58f529da5ceb1798","carrier":"","af_preinstalled":"false","iaecounter":"1","sdk":"26","app_version_name":"2.5.0","device":"F5122","platformextension":"android_reactNative","cksm_v1":"8a04f49349ebf2dc5f25b9881e3fdfd0c8","rfr":{"val":"af_tranid=5jwI8-3uS4tzB0SYaSuWRQ&shortlink=dailydeals&pid=dailydeals&is_retargeting=true&af_dp=eatsy:\/\/highlight-details?highlightID=6","code":"0","clk":"1559700029","install":"1559621738"}}
com.eatsy I/AppsFlyer_4.9.0: response code: 200
com.eatsy I/AppsFlyer_4.9.0: Calling server for attribution url: https://api.appsflyer.com/install_data/v3/com.eatsy?devkey=S********************P&device_id=1559700059471-6851905248027335411
com.eatsy D/AppsFlyer_4.9.0: iscache=null caching conversion data
com.eatsy D/AppsFlyer: install attribute: af_status = Organic
com.eatsy D/AppsFlyer: install attribute: af_message = organic install
com.eatsy D/AppsFlyer: install attribute: is_first_launch = true
com.eatsy I/ReactNativeJS: 'TCL: AppsFlyer onInstall', '{"status":"success","type":"onInstallConversionDataLoaded","data":{"af_status":"Organic","af_message":"organic install","is_first_launch":"true"}}'
```

**Additional Information**

- This issue only happens on Android, it works fine on iOS.
- Despite the `onInstallConversionData` got called with organic result on the device, the install count still tracked correctly on the Dashboard:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/12025966/58926790-952a9f80-8776-11e9-9a18-872c2dd88df1.png">

- The device was whitelisted
<img width="877" alt="image" src="https://user-images.githubusercontent.com/12025966/58927181-db343300-8777-11e9-95b5-07587895ede1.png">

- Using AppsFlyer Test App to test the non-organic install will always failed in the last step.

**Versions**
"react-native": "0.55.4"
"react-native-appsflyer": "^1.4.2"

**Comment by af-fess** [comment]
Hey, did you whitelisted android device?

**Comment by pqkluan** [comment]
@af-fess The device was **whitelisted**
![](https://user-images.githubusercontent.com/12025966/58927181-db343300-8777-11e9-95b5-07587895ede1.png)

**Comment by pqkluan** [comment]
After I worked with the AppsFlyer support, the issue has been fixed.

The fix was applied on the AppsFlyer back-end side so there are no additional changes required on my app. 

Big thanks for the AppFlyer support team.

**Comment by johnkennethfurog** [comment]
Hi guys, I am also encountering this issue, any workaround for this? thanks

**Comment by m4r00p** [comment]
Same here any luck with solving this issue?

**Comment by curiousdustin** [comment]
@af-fess Can you please explain the whitelisting a bit?

I was also having this issue. Deferred linking parameters would not be available, and onInstallConversionDataLoaded callback would always return organic.

After I whitelisted my device in the AppsFlyer dashboard, this issue was resolved and it worked as expected.

However, obviously, we cannot whitelist all our user's devices... What exactly is whitelisting accomplishing, and how can I be certain things will work for real users?

**Comment by pqkluan** [comment]
Hi @curiousdustin,

The purpose of whitelist was written here:
https://support.appsflyer.com/hc/en-us/articles/207031996-Registering-test-devices-

In-short, when we implement the AppsFlyer SDK, we need a way re-use the device to test the attributions (otherwise you need a new device every time you need to test the flow).

For example:
> You implement the AppsFlyer for the first time.
> You use your test device to click on the ads/link.
> You see there are a changes on the dashboard afterward.

But if you click the link again, the metrics on the dashboard won't change, because AppsFlyer already remember your device id. So you cannot know if the implementation is working or not.

Whitelist a device is telling AppsFlyer to NOT remember your device, and every time you use the device to engage with the ads/link. AppsFlyer will treat it as a brand new device (user).

**Comment by curiousdustin** [comment]
@pqkluan thank you. This makes sense now. 

But, what if we want to use a OneLink to do deferred linking, AND have it work more than once on a given device (for real users)? Obviously we cannot whitelist everyone. 

For instance if a user installed my app 30 days ago, then uninstalled, but now they encounter a link again for whatever reason and reinstall. I would still like to have access to the (deferred) data from the link. Is this possible?

**Comment by pqkluan** [comment]
@curiousdustin 

So you want to get the metadata part when you tap on the link again, right?
Then you should also check the `onAppOpenAttribution` callback.

https://support.appsflyer.com/hc/en-us/articles/217108646-React-Native-plugin#api-reference-onappopenattribution

Here is my old code for extracting data from AppsFlyer:

```typescript
function initAppsFlyer() {
  // DO NOT REMOVE onInstallConversionData register
  // onAppOpenAttribution will not work without it for whatever reason
  AppsFlyer.onInstallConversionData(handleOnInstallConversionData);
  AppsFlyer.onAppOpenAttribution(handleOnAppOpenAttribution);

  const onInitSuccess = () =>
    console.log('Init successful', { at: 'AppsFlyer initSdk' });
  const onInitError = (error: string) =>
    console.error(new Error(error), { at: 'AppsFlyer initSdk' });

  AppsFlyer.initSdk(
    {
      devKey,
      appId: ENV.iOSAppId, // iOS only
      isDebug: __DEV__,
    },
    onInitSuccess,
    onInitError
  );
}

function handleOnInstallConversionData(event: any) {
  // Do nothing if this is not the first launch
  const isFirstLaunch = event?.data?.is_first_launch ?? false;
  if (isFirstLaunch === 'false' || isFirstLaunch === false) return;

  const af_dp = event?.data?.af_dp;
  const link = event?.data?.link;
  const url = af_dp ?? link;
  if (url === undefined) return;

  // TODO: handle url
}

function handleOnAppOpenAttribution(event: Object) {
  const af_dp = event?.data?.af_dp;
  const link = event?.data?.link;
  const url = af_dp ?? link;
  if (url === undefined) return;

  // TODO: handle url
}
```

I haven't using AppsFlyer in last 2 years so this is all I could help.

**Comment by gustavogialimvizir** [comment]
@pqkluan thank you for the contribution.

I have the same doubt that @curiousdustin, someone knows if the condition below should work without whitelist a device?

For instance, if a user installed my app 30 days ago, then uninstalled it, but now they encounter a link again for whatever reason and reinstall. I would still like to have access to the (deferred/onInstallConversionData callback) data from the link. Is this possible?

Trying here in devices that already installed the app one time and now used the deep link I did not get the`onInstallConversionData` callback called, just after putting the device as a whitelist that it worked.

Would be interesting an Appsflyer member to answer this question.
