### ISSUE TITLE
trackAppLaunch is called during initSDK.

### ISSUE THREAD

**Issue by alexxv** [AppsFlyerSDK/react-native-appsflyer#9]
Hey, 

`initSDK` tracks app launch, in my scenario I want to set `customerID` and other properties before app launch is tracked. 
Can you separate `trackAppLaunch` into a separate call. So it can be called explicitly?

Thanks

Alex

**Comment by af-fess** [comment]
`trackAppLaunch` is a part of initialization of SDK and it uses the same *carrier* as track Event. `initSDK` name is a legacy name used mostly for, hybrid apps.

**Comment by alexxv** [comment]
Is there a way I can separate sdk initialization from app launch tracking?
I need to set customerId between those two

**Comment by af-fess** [comment]
As I described in other issue we aggregate `customerId` but don't send it to raw data report. I suggest you to ask our [Support](https://support.appsflyer.com/hc/en-us) about
