### ISSUE TITLE
New Release for bugfix #84

### ISSUE THREAD

**Issue by arenarius** [AppsFlyerSDK/react-native-appsflyer#94]
Hello,

I've run into the `getCurrentActivity` #82  bug, and saw that a fix was merged on May 7 #84. 
The latest release is from February (1.4.1/2). 

It'd be a great help if you could publish a new release.

Many thanks!

**Comment by wesfieldj** [comment]
@arenarius done. v1.4.3 was published. 

Please let us know if there are still any issues.

Thanks!
